-- INSERT INTO movies (name, category) VALUES ('film', 'HORROR');
-- INSERT INTO movies (name, category) VALUES ('film_2', 'COMEDY');
--
--
-- CREATE TABLE movies (
--                         ID bigint AUTO_INCREMENT PRIMARY KEY,
--                         name VARCHAR(120),
--                         category VARCHAR(120),
--                         is_available BOOLEAN NOT NULL DEFAULT false
-- );